/**
 * Business Reports - Weekly and Monthly
 *
 * Scheduled functions that send weekly and monthly performance
 * reports to business owners.
 *
 * Part of the Automated Engagement System - Part B (Phase 5)
 */

import * as functions from "firebase-functions/v1";
import {
  getActiveBusinesses,
  sendBusinessNotification,
  isEmailNotificationEnabled,
  getBusinessStats,
} from "./emailSender";
import {
  getWeeklyReportEmail,
  getMonthlyReportEmail,
} from "./emailTemplates";

// ============================================================================
// Monthly Report
// ============================================================================

/**
 * Send monthly performance report to all active businesses
 * Schedule: 1st of every month at 10 AM Colombia time
 * Includes platform update generated by Gemini
 */
export const sendMonthlyReports = functions
  .runWith({
    secrets: ["RESEND_API_KEY"],
    timeoutSeconds: 540,
    memory: "512MB",
  })
  .pubsub.schedule("0 10 1 * *")
  .timeZone("America/Bogota")
  .onRun(async (context) => {
    console.log("Starting monthly reports...");

    try {
      const businesses = await getActiveBusinesses();
      console.log(`Sending monthly reports to ${businesses.length} businesses`);

      // Calculate date range (last 30 days / previous month)
      const endDate = new Date();
      const startDate = new Date();
      startDate.setDate(startDate.getDate() - 30);

      let sent = 0;
      let skipped = 0;

      // Process businesses in parallel batches for better performance
      const BATCH_SIZE = 10;

      for (let i = 0; i < businesses.length; i += BATCH_SIZE) {
        const batch = businesses.slice(i, i + BATCH_SIZE);

        const results = await Promise.all(
          batch.map(async (business) => {
            // Check if email notifications are enabled
            if (!(await isEmailNotificationEnabled(business.id))) {
              return { success: false, reason: "disabled" };
            }

            try {
              // Get business stats for the month
              const stats = await getBusinessStats(business.id, startDate, endDate);

              const emailContent = getMonthlyReportEmail(business, {
                stats: {
                  views: stats.views,
                  saves: stats.saves,
                  clicks: stats.clicks,
                },
                top_promotions: stats.topPromotions,
              });

              const result = await sendBusinessNotification(
                business,
                "monthly_report",
                emailContent,
                {
                  period: "monthly",
                  stats: {
                    views: stats.views,
                    saves: stats.saves,
                    clicks: stats.clicks,
                  },
                }
              );

              return result;
            } catch (error) {
              console.error(
                `Error sending monthly report to ${business.id}:`,
                error
              );
              return { success: false, reason: "error" };
            }
          })
        );

        // Count results
        for (const result of results) {
          if (result.success) {
            sent++;
          } else {
            skipped++;
          }
        }

        // Rate limiting between batches
        if (i + BATCH_SIZE < businesses.length) {
          await new Promise((resolve) => setTimeout(resolve, 1000));
        }
      }

      console.log(`Monthly reports complete: ${sent} sent, ${skipped} skipped`);
      return null;
    } catch (error) {
      console.error("Error sending monthly reports:", error);
      throw error;
    }
  });

// ============================================================================
// Manual Trigger Helpers (for testing)
// ============================================================================

/**
 * Manually send weekly report to a specific business
 */
export async function sendWeeklyReportToBusiness(
  businessId: string
): Promise<{ success: boolean; error?: string }> {
  const { getBusinessInfo } = await import("./emailSender");

  const business = await getBusinessInfo(businessId);
  if (!business) {
    return { success: false, error: "Business not found" };
  }

  const endDate = new Date();
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - 7);

  const stats = await getBusinessStats(businessId, startDate, endDate);

  const emailContent = getWeeklyReportEmail(business, {
    stats: {
      views: stats.views,
      saves: stats.saves,
      clicks: stats.clicks,
    },
    top_promotions: stats.topPromotions,
  });

  const result = await sendBusinessNotification(
    business,
    "weekly_report",
    emailContent,
    {
      period: "weekly",
      stats: {
        views: stats.views,
        saves: stats.saves,
        clicks: stats.clicks,
      },
    }
  );

  return result;
}

/**
 * Manually send monthly report to a specific business
 */
export async function sendMonthlyReportToBusiness(
  businessId: string
): Promise<{ success: boolean; error?: string }> {
  const { getBusinessInfo } = await import("./emailSender");

  const business = await getBusinessInfo(businessId);
  if (!business) {
    return { success: false, error: "Business not found" };
  }

  const endDate = new Date();
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - 30);

  const stats = await getBusinessStats(businessId, startDate, endDate);

  const emailContent = getMonthlyReportEmail(business, {
    stats: {
      views: stats.views,
      saves: stats.saves,
      clicks: stats.clicks,
    },
    top_promotions: stats.topPromotions,
  });

  const result = await sendBusinessNotification(
    business,
    "monthly_report",
    emailContent,
    {
      period: "monthly",
      stats: {
        views: stats.views,
        saves: stats.saves,
        clicks: stats.clicks,
      },
    }
  );

  return result;
}
